// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: greeting.sql

package db

import (
	"context"
)

const addGreeting = `-- name: AddGreeting :one
INSERT INTO greeting(content)
VALUES ($1)
RETURNING id
`

func (q *Queries) AddGreeting(ctx context.Context, content string) (int64, error) {
	row := q.db.QueryRow(ctx, addGreeting, content)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getGreeting = `-- name: GetGreeting :one
SELECT id, content
FROM greeting
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetGreeting(ctx context.Context, id int64) (*Greeting, error) {
	row := q.db.QueryRow(ctx, getGreeting, id)
	var i Greeting
	err := row.Scan(&i.ID, &i.Content)
	return &i, err
}
